# Site Info
title:              "Ying Hua's personal blog"
description:        "Welcome to Ying Hua's personal blog!"
author_name:        "Ying Hua" # change this to your name
logo_url:           https://avatars3.githubusercontent.com/u/2174068?s=100&v=4

# Site Settings
url:                https://herohua.github.io # main url
baseurl:            /index
permalink:          /:title # Post permalink
timezone:           Asia/Chongqing # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"

# Build settings
remote_theme: heiswayi/the-plain
